<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>kudos_perception</name>
  <version>0.1.0</version>
  <description>2026 AUTO RACE 카메라 인지 노드 (KUDOS)</description>
  <maintainer email="cosmosxyz4@gmail.com">고균명</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>ar_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
